**NumPy In Python**

**Advantages of NumPy :-**
1.   **Allows Several Mathematical Operations**
2.   **Faster Operations**



In [38]:
import numpy as np

**List VS NumPy Array - Time Taken**

In [39]:
from time import process_time

**Time Taken By List**

In [40]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0016100770000022635


**Time Taken By NumPy Array**

In [41]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 #np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)

0.0004902259999965963


**NumPy Arrays**

In [42]:
np_arr = np.array([1, 2, 3, 4, 5, "Hello"])
print(type(np_arr))
print(np_arr)

<class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'Hello']


In [43]:
# Create a 2D array (3x3) initialized with zeros
array_zeros = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
print(array_zeros.shape)
print(array_zeros)

(3, 3)
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [44]:
#Create a 3D array (2x2x2) initialized with ones
array_ones = np.array([[[1, 1], [1, 1]], [[1, 1], [1, 1]]])
print(array_ones.shape)
print(array_ones)

(2, 2, 2)
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [45]:
# Create a 2D array (4x2) initialized with a specific value (e.g., 5)
array_custom_value = np.full((4, 2), 5)
print(array_custom_value.shape)
print(array_custom_value)

(4, 2)
[[5 5]
 [5 5]
 [5 5]
 [5 5]]


In [46]:
# Create a 3D array (2x2x2) initialized with ones
array_ones = np.array([[[1, 1], [1, 1]], [[1, 1], [1, 1]]])
print("\nArray of ones:")
print(array_ones)
print("Data type:", array_ones.dtype)


Array of ones:
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
Data type: int64


In [47]:
# Create a 2D array (3x4) initialized with zeros
zeros_array = np.zeros((3, 4))
print("\nArray of zeros (3x4):")
print(zeros_array)
print("Data type:", zeros_array.dtype)


Array of zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Data type: float64


In [48]:
# Create a 2D array (2x3) initialized with empty values (uninitialized)
empty_array = np.empty((2, 3))
print("\nEmpty array (2x3):")
print(empty_array)
print("Data type:", empty_array.dtype)


Empty array (2x3):
[[4.83474993e-310 0.00000000e+000 2.14321575e-312]
 [2.33419537e-312 2.44029516e-312 2.66532324e-260]]
Data type: float64


In [49]:
# Create a 2D array (2x2) of integers
int_array = np.array([[1, 2], [3, 4]], dtype=np.int32)
print("\nArray of integers:")
print(int_array)
print("Data type:", int_array.dtype)


Array of integers:
[[1 2]
 [3 4]]
Data type: int32


In [50]:
# Create a 2D array (2x2) of floats
float_array = np.array([[1.5, 2.5], [3.7, 4.2]], dtype=np.float64)
print("\nArray of floats:")
print(float_array)
print("Data type:", float_array.dtype)


Array of floats:
[[1.5 2.5]
 [3.7 4.2]]
Data type: float64


In [51]:
#Create an Identity Matrix
np_identity = np.eye(4)
print(np_identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [52]:
# Create a 2D array (3x3) initialized with random values between 0 and 1
random_array = np.random.random((3, 3))
print("\nRandom array (3x3):")
print(random_array)
print("Data type:", random_array.dtype)


Random array (3x3):
[[0.27293061 0.54563204 0.94311395]
 [0.58346908 0.29125861 0.55356336]
 [0.86332647 0.94402614 0.448327  ]]
Data type: float64


In [53]:
random_array_int = np.random.randint(10, 100, (3, 3))
print("\nRandom array (3x3):")
print(random_array_int)
print("Data type:", random_array_int.dtype)


Random array (3x3):
[[17 68 19]
 [67 49 33]
 [54 40 92]]
Data type: int64


In [54]:
#Convert List to a NumnPy Array
list1 = [1, 2, 4, 5, 3]

np_array1 = np.asarray(list1)

type(np_array1)

numpy.ndarray

**Numpy For Machine Learning**

**Random Number Generation for Initializing Weights and Data Splitting**

In [55]:
# Generate random numbers from a uniform distribution
random_uniform = np.random.rand(3, 3)
print("Random numbers from a uniform distribution:")
print(random_uniform)

Random numbers from a uniform distribution:
[[0.47072708 0.69638524 0.23970126]
 [0.62346505 0.38655622 0.95927642]
 [0.51724138 0.64311135 0.16845198]]


In [56]:
# Generate random numbers from a normal distribution
random_normal = np.random.randn(3, 3)
print("\nRandom numbers from a normal distribution:")
print(random_normal)


Random numbers from a normal distribution:
[[-0.92623136  2.09529159  1.38674803]
 [-0.20547576 -0.17689792 -0.37741601]
 [-0.08875301 -0.43267671 -0.61807481]]


In [57]:
# Generate random integers within a specified range
random_integers = np.random.randint(low=1, high=10, size=(3, 3))
print("\nRandom integers within a range:")
print(random_integers)


Random integers within a range:
[[1 1 9]
 [3 5 1]
 [8 1 6]]


In [59]:
# Shuffle an array (useful for data shuffling before splitting)
original_array = np.array([1, 2, 3, 4, 5])
shuffled_array = np.random.permutation(original_array)
print("\nShuffled Array:")
print(shuffled_array)


Shuffled Array:
[4 3 5 1 2]


**Mathematical Functions for Data Transformation**

In [60]:
# Calculate element-wise logarithm
array = np.array([1, 10, 100])
log_values = np.log(array)
print("Logarithm of Array Elements:")
print(log_values)

Logarithm of Array Elements:
[0.         2.30258509 4.60517019]


In [61]:
# Calculate element-wise exponential
exp_values = np.exp(array)
print("\nExponential of Array Elements:")
print(exp_values)


Exponential of Array Elements:
[2.71828183e+00 2.20264658e+04 2.68811714e+43]


In [62]:
# Calculate element-wise square root
sqrt_values = np.sqrt(array)
print("\nSquare Root of Array Elements:")
print(sqrt_values)


Square Root of Array Elements:
[ 1.          3.16227766 10.        ]


**Array Manipulation for Data Preprocessing**

In [63]:
# Reshape an array for compatibility with machine learning models
original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = original_array.reshape(2, 3)
print("Reshaped Array:")
print(reshaped_array)

Reshaped Array:
[[1 2 3]
 [4 5 6]]


In [64]:
# Flatten an array to 1D (useful for input data preparation)
flattened_array = reshaped_array.flatten()
print("\nFlattened Array:")
print(flattened_array)


Flattened Array:
[1 2 3 4 5 6]


In [65]:
# Concatenate arrays along axis 1 (columns) for feature concatenation
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array = np.concatenate((array1, array2), axis=1)
print("\nConcatenated Array along axis 1:")
print(concatenated_array)


Concatenated Array along axis 1:
[[1 2 5 6]
 [3 4 7 8]]
